apiVersion: v1
kind: Secret
metadata:
  name: goodnotes-takehome-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: goodnotes-takehome
  type: git
  url: git@github.com:LeoDomeneghetti/goodnotes-takehome-sre.git
  sshPrivateKey: |