apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app-deployment
  labels:
    app: foo-app
    tier: backend
spec:
  template:
    metadata:
        name: foo-app
        namespace: goodnotes-takehome
        labels:
          app: foo-app
          namespace: goodnotes-takehome
          tier: backend
    spec:
      containers:
        - name: foo-app
          image: leodomeneghetti/foo-app:v1.0.0
      nodeSelector:
        kubernetes.io/hostname: "goodnotes-multi-node-worker"
  replicas: 1
  selector:
    matchLabels:
      app: foo-app
      namespace: goodnotes-takehome
      tier: backend

