apiVersion: v1
kind: Service
metadata:
  name: foo-app-service
  labels:
    namespace: goodnotes-takehome
spec:
  ports:
  - name: foo-port
    port: 8082
    targetPort: 5000
  selector:
    app: foo-app
    namespace: goodnotes-takehome
    tier: backend