kind: Service
apiVersion: v1
metadata:
  name: foo-app-service
  namespace: goodnotes-takehome
  labels:
    namespace: goodnotes-takehome
spec:
  type: LoadBalancer
  selector:
    app: foo-app
    namespace: goodnotes-takehome
    tier: backend
  ports:
  - port: 8082
    targetPort: 5000